travis:
  secure:
    BINSTAR_TOKEN: w7VAWALynMLnxo/3c6qFlO9/Q33o4hrR2iOU2LTzzBnfbvwaJJef47s7nqwxIEozBPDYig8gPIhChvJ+XCpxlueeCl5mv7f2h3PcxW0+n1hs1+/mOgmrxNNkbO4vXKUs216NUOw1+ppekoiKEX++SkjMECFuXvPTQ1Goo6LUua2adswYmd/EKJ2jMEoeG5I4q2YQxg0OmFGY2BGMsnBT/doz1VIOAx5Ifuk1I6t5Dx9o/8/H9XGmw7A6u/mi09If7Y0NRpAZqOj93rKR3bskqt1DiyGnv3yT6/9/rYnKnkDTXrpsEdNfbrICvosdj0H8tFC1pvDu2v08RRYZwNiFjXH84LrN9afPuyfcC+GttBfVQSqUPvc/BhVC+yfDPQ9qCLcXxQPVWvvFBnKdQn4Gp0lpx7MX84ZRHbD86w6E2NzMrKd36vWexIBCWPnUBDv0xCw3XzCy38CXR+k5Be9BtESlKl+H8exCm6v0izING7F5F4iQSMtxresLZvTwv0LzmZpbacmnzreKDB1sejD/iu1qEgUJNn2r3nbPNlfMp/Xn0mom3P3gpYpCjaBWhbUGNQpuc3S4Ph/iVzS/oEdOwMh00CO/gFhXi0VaENnvQdZZbi2sjzSCANGm4ARf1sivK1cIf7cxMl3wCpbMl/SUcUU7VubGy3MrO//mKk2yxqs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
